# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  actions_path './actions'

  MASTER_PATH = "https://github.com/CocoaPods/Specs,https://gitee.com/yan_long/ylspecs.git"
  PRIVATE_PATH = "https://github.com/baoyanlong/YLSwiftKit.git"
  PRIVATE_SPEC = "YLSpecs"
  SOURCES = [PRIVATE_PATH, MASTER_PATH]

  desc "Release new private pod version"
  lane :do_publish_lib do |options|
    target_version = options[:version]
    # CJKit-Swift.podspec
    lib            = "YLSwiftKit"
    lib_path       = "#{lib}.podspec"

    #git_pull
    #pod_install(name: PRIVATE_SPEC)

    # http://docs.fastlane.tools/actions/pod_lib_lint/#pod_lib_lint
    pod_lib_lint(podspec: lib_path, 
      verbose: false, 
      allow_warnings: true, 
      use_libraries: true, 
      sources: SOURCES, 
      use_bundle_exec: true, 
      fail_fast: true, 
      use_modular_headers: true,
      skip_import_validation: true)

    version_bump_podspec(path: lib_path, version_number: target_version) # 更新 podspec
    git_commit_all(message: "Bump version to #{target_version}") # 提交版本号修改
    add_git_tag(tag: target_version) # 设置 tag
    push_to_git_remote # 推送到 git 仓库

    #pod_push(path: lib_path, 
      #repo: PRIVATE_SPEC, 
     # allow_warnings: true, 
    #  use_libraries: true, 
     # sources: SOURCES, 
     # use_modular_headers: true,
    #  skip_import_validation: true) # 提交到 CocoaPods私有库
    pod_push(path: lib_path, 
      allow_warnings: true) # 提交到 CocoaPods公有库
  end

end
